"""warden approval added

Revision ID: 375b37258e9c
Revises: f979ada281fe
Create Date: 2025-07-08 12:36:23.042569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375b37258e9c'
down_revision = 'f979ada281fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warden_approval', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('warden_approval')

    # ### end Alembic commands ###
