"""Add exited_at column

Revision ID: 3e0545bc9c0a
Revises: e359f45dd6b6
Create Date: 2025-07-20 11:27:00.658914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0545bc9c0a'
down_revision = 'e359f45dd6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('exited_at')

    # ### end Alembic commands ###
