"""Add idno, branch, and batch to User model

Revision ID: 85c512e39fdf
Revises: dbeea713eaf3
Create Date: 2025-07-09 16:11:43.363053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c512e39fdf'
down_revision = 'dbeea713eaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_idno'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_idno'), ['idno'])
        batch_op.drop_column('p_email')

    # ### end Alembic commands ###
