"""warden approval added

Revision ID: d9c91f637359
Revises: 70149be3aa61
Create Date: 2025-07-08 10:40:54.801254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c91f637359'
down_revision = '70149be3aa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_warden', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('warden_approval', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('warden_approval')
        batch_op.drop_column('request_warden')

    # ### end Alembic commands ###
