"""Add idno, branch, and batch to User model

Revision ID: dbeea713eaf3
Revises: 375b37258e9c
Create Date: 2025-07-09 15:54:50.826162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbeea713eaf3'
down_revision = '375b37258e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idno', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint("uq_user_idno", ['idno'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('batch')
        batch_op.drop_column('branch')
        batch_op.drop_column('idno')

    # ### end Alembic commands ###
