"""warden approval added

Revision ID: e089e3525a36
Revises: d9c91f637359
Create Date: 2025-07-08 10:41:56.895280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e089e3525a36'
down_revision = 'd9c91f637359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('request_warden')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_warden', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
