"""Add warden_status column

Revision ID: e359f45dd6b6
Revises: 85c512e39fdf
Create Date: 2025-07-19 22:27:31.631893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e359f45dd6b6'
down_revision = '85c512e39fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warden_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('warden_status')

    # ### end Alembic commands ###
