"""Add security exit column

Revision ID: e44462951691
Revises: 3e0545bc9c0a
Create Date: 2025-07-20 11:28:58.166789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44462951691'
down_revision = '3e0545bc9c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_exit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('security_exit')

    # ### end Alembic commands ###
