"""warden approval added

Revision ID: f979ada281fe
Revises: e089e3525a36
Create Date: 2025-07-08 12:35:32.304025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f979ada281fe'
down_revision = 'e089e3525a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.drop_column('warden_approval')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warden_approval', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
